# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:
  nginx:
    container_name: nginx_container
    restart: always
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
     - ./client/build:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask

  flask:
    container_name: flask_container
    restart: always
    image: flask
    build: ./server
    volumes:
    - ./server:/usr/src/app/server
    env_file:
     - .env
